name: dartmixins
description: A mixin library that provides support for the usual functional suspects (each, map, reduce, filter...) without extending any core Dart objects with a jQuery-like interface.
authors:
 - Demis Bellot
 - Adam Singer <financeCoding@gmail.com>
homepage: https://github.com/Dartist/Mixins
version: 0.0.2
environment:
  sdk: '>=0.5.3'
dev_dependencies:
  hop: '>=0.22.1+1'